application_bde_homepage:
    pattern:  /
    defaults: { _controller: ApplicationPageBundle:Page:index }

application_bde_history:
    pattern:  /history
    defaults: { _controller: ApplicationPageBundle:Page:history }

application_bde_cotisation:
    pattern:  /cotisation
    defaults: { _controller: ApplicationPageBundle:Page:cotisation }

application_bde_association:
    pattern:  /association
    defaults: { _controller: ApplicationPageBundle:Page:association }

application_bde_partnership:
    pattern:  /partnership
    defaults: { _controller: ApplicationPageBundle:Page:partnership }

application_bde_team:
    pattern:  /team
    defaults: { _controller: ApplicationPageBundle:Page:team }

application_bde_programme:
    pattern:  /programme
    defaults: { _controller: ApplicationPageBundle:Page:programme }

application_bde_privacy_policy:
    pattern:  /regles-de-confidentialite
    defaults: { _controller: ApplicationPageBundle:Page:privacyPolicy }
