<?php

namespace Application\StudentBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Application\StudentBundle\Entity\Student;

/**
 * StudentHasClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentHasClubRepository extends EntityRepository
{
	public function findClubsbyStudent(Student $student)
	{
		return $this
			->createQueryBuilder('shc')
			->select('IDENTITY(shc.club_director)', 'IDENTITY(shc.club_member)')
			->where('shc.student = :student')
				->setParameter('student', $student)
			->getQuery()
			->getResult()
		;
	}
}
