<?php

namespace Application\StudentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StudentHasClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentHasClubRepository extends EntityRepository
{
}
