Application\PoudlardBundle\Entity\House:
    type: entity
    table: poudlard__house
    repositoryClass: Application\PoudlardBundle\Repository\HouseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        score:
            type: integer
    oneToMany:
        clubs:
            targetEntity: Application\BDEBundle\Entity\Club
            mappedBy: house
            cascade: ["all"]
    lifecycleCallbacks: {  }
