application_student_search:
    path:     /api/fairpay/{query}
    defaults: { _controller: ApplicationStudentBundle:Student:search }

application_student_am_i_contributor:
    path:     /suis-je-cotisant
    defaults: { _controller: ApplicationStudentBundle:Student:amIContributor }

application_student_search_clubs:
    path:     /clubs-by-student/{student}
    defaults: { _controller: ApplicationStudentBundle:Student:clubsByStudent, _format:json }
    requirements:
        _format: json
        _method:  GET
        student: \d{7}
