services:
    application_esiee_games.admin.points:
        class: Application\ESIEEGamesBundle\Admin\PointsAdmin
        arguments: [~, Application\ESIEEGamesBundle\Entity\Points, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Points }
