Application\StudentBundle\Entity\Student:
    type: entity
    table: bde__student
    repositoryClass: Application\StudentBundle\Repository\StudentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: NONE
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        email:
            type: string
            length: 255
        isRefunded:
            type: boolean
            nullable: true
    oneToMany:
        clubs:
            targetEntity:  Application\StudentBundle\Entity\StudentHasClub
            mappedBy: student
            orphanRemoval: true
    lifecycleCallbacks: {  }
