<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\NewsBundle\Entity;

use Sonata\NewsBundle\Entity\BasePost as BasePost;
use Doctrine\ORM\Mapping as ORM;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Post extends BasePost
{
    /**
     * @var integer $id
     */
    protected $id;

    private $event;

    private $photo;

    private $thumbnail;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set event
     *
     * @param \Application\BDEBundle\Entity\Event $event
     * @return Post
     */
    public function setEvent(\Application\BDEBundle\Entity\Event $event = null)
    {
        $this->event = $event;

        return $this->event;
    }

    /**
     * Get event
     *
     * @return \Application\BDEBundle\Entity\Event $event
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Set photo
     *
     * @param \Application\Sonata\MediaBundle\Entity\Media $photo
     * @return Post
     */
    public function setPhoto(\Application\Sonata\MediaBundle\Entity\Media $photo = null)
    {
        $this->photo = $photo;

        return $this->photo;
    }

    /**
     * Get photo
     *
     * @return \Application\Sonata\MediaBundle\Entity\Media $photo
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * Set thumbnail
     *
     * @param \Application\Sonata\MediaBundle\Entity\Media $thumbnail
     * @return Post
     */
    public function setThumbnail(\Application\Sonata\MediaBundle\Entity\Media $thumbnail = null)
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }

    /**
     * Get thumbnail
     *
     * @return \Application\Sonata\MediaBundle\Entity\Media 
     */
    public function getThumbnail()
    {
        return $this->thumbnail;
    }

    public function __toString()
    {
        return $this->publicationDateStart->format('d/m/Y').' - '.$this->title.' (par '.$this->author.') '.(isset($this->event) ? '(le '.$this->event->getDateStart()->format('d/m/Y').')' : '');
    }
}
