<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\NewsBundle\Entity;

use Sonata\NewsBundle\Entity\BasePost as BasePost;
use Doctrine\ORM\Mapping as ORM;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Post extends BasePost
{
    /**
     * @var integer $id
     */
    protected $id;

    private $event;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set event
     *
     * @param \Application\BDEBundle\Entity\Event $event
     * @return Post
     */
    public function setEvent(\Application\BDEBundle\Entity\Event $event = null)
    {
        $this->event = $event;

        return $this->event;
    }

    /**
     * Get event
     *
     * @return \Application\BDEBundle\Entity\Event $event
     */
    public function getEvent()
    {
        return $this->event;
    }
}