application_bde_homepage:
    pattern:  /
    defaults: { _controller: ApplicationBDEBundle:Default:index }

application_bde_aboutus:
    pattern:  /about-us
    defaults: { _controller: ApplicationBDEBundle:Default:aboutus }

application_bde_history:
    pattern:  /history
    defaults: { _controller: ApplicationBDEBundle:Default:history }

application_bde_partnership:
    pattern:  /partnership
    defaults: { _controller: ApplicationBDEBundle:Default:partnership }

application_bde_lost_property:
    pattern:  /objets/trouves.{_format}
    defaults: { _controller: ApplicationBDEBundle:LostProperty:index, _format:html }
    requirements:
        _format: html|json|xml
        _method:  GET

application_bde_eat_traffic:
    pattern:  /eat/traffic
    defaults: { _controller: ApplicationBDEBundle:Default:eatTraffic }

application_bde_good_plan:
    pattern:  /bons/plans
    defaults: { _controller: ApplicationBDEBundle:Bargain:index }

application_bde_breguet_shop:
    pattern:  /shop
    defaults: { _controller: ApplicationBDEBundle:Shop:index }

application_bde_breguet_shop_filter:
    pattern:  /shop/filter/{id}
    defaults: { _controller: ApplicationBDEBundle:Shop:index }
    requirements:
        id: \w+

application_bde_breguet_shop_show:
    pattern:  /shop/view/{id}
    defaults: { _controller: ApplicationBDEBundle:Shop:view }
    requirements:
        id: \d+

application_bde_club:
    pattern:  /clubs.{_format}
    defaults: { _controller: ApplicationBDEBundle:Club:index, _format:html }
    requirements:
        _format: html|json|xml
        _method:  GET

application_bde_club_get:
    pattern:  /clubs/{id}.{_format}
    defaults: { _controller: ApplicationBDEBundle:Club:getClub, _format:html }
    requirements:
        id: \d+
        _format: html|json|xml
        _method:  GET

application_bde_club_show:
    pattern:  /clubs/view/{id}-{shortcode}
    defaults: { _controller: ApplicationBDEBundle:Club:show }
    requirements:
        id: \d+

application_bde_events:
    pattern: /events.{_format}
    defaults: { _controller: ApplicationBDEBundle:Event:index, _format:html }
    requirements:
        _format: html|json|xml|ics
        _method:  GET