application_bde_club_trombi:
    pattern:  /clubs/trombi/{id}.{_format}
    defaults: { _controller: ApplicationBDEBundle:Club:getClubTrombi, _format:pdf }
    requirements:
        id: \d+
        _format: jpg|pdf
        _method:  GET

application_bde_club:
    pattern:  /clubs.{_format}
    defaults: { _controller: ApplicationBDEBundle:Club:index, _format:html }
    requirements:
        _format: html|json|xml
        _method:  GET

application_bde_club_get:
    pattern:  /clubs/{id}.{_format}
    defaults: { _controller: ApplicationBDEBundle:Club:getClub, _format:html }
    requirements:
        id: \d+
        _format: html|json|xml
        _method:  GET

application_bde_club_show:
    pattern:  /clubs/view/{id}-{shortcode}
    defaults: { _controller: ApplicationBDEBundle:Club:show }
    requirements:
        id: \d+

application_bde_events:
    pattern: /events.{_format}
    defaults: { _controller: ApplicationBDEBundle:Event:index, _format:html }
    requirements:
        _format: html|json|xml|ics
        _method:  GET

application_bde_clubs_fees_refund:
    pattern:  /clubs/remboursement-cotisation
    defaults: { _controller: ApplicationBDEBundle:Club:feesRefund }
    requirements:
        _method:  GET
