parameters:

services:
    bde.admin.product:
        class: Application\BDEBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Breguet Shop", label: "Article", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Application\BDEBundle\Entity\Product
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationBDEBundle]]
    bde.admin.product_category:
        class: Application\BDEBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Breguet Shop", label: "Catégorie", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Application\BDEBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationBDEBundle]]
    bde.admin.club:
        class: Application\BDEBundle\Admin\ClubAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Associatif", label: "Club", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Application\BDEBundle\Entity\Club
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationBDEBundle]]
    bde.admin.club_category:
        class: Application\BDEBundle\Admin\ClubCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Associatif", label: "Catégorie", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Application\BDEBundle\Entity\ClubCategory
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationBDEBundle]]
    bde.admin.event:
        class: Application\BDEBundle\Admin\EventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Associatif", label: "Événement", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Application\BDEBundle\Entity\Event
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationBDEBundle]]
    bde.decoder.ics:
        class: Application\BDEBundle\Decoder\ICSDecoder
    bde.handler.ics:
        class: Application\BDEBundle\Handler\ICSHandler
        arguments:
            - "@bde.decoder.ics"
    bde.view_handler.ics:
        parent: fos_rest.view_handler.default
        calls:
            - ['registerHandler', [ 'ics', ["@bde.handler.ics", 'createResponse'] ] ]
    bde.admin.post:
        class: Application\BDEBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Blog", label: "News", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - %sonata.news.admin.post.entity%
            - %sonata.news.admin.post.controller%
        calls:
            - [ setTranslationDomain, [%sonata.news.admin.post.translation_domain%]]
            - [ setUserManager, [@fos_user.user_manager]]
            - [ setPoolFormatter, [@sonata.formatter.pool]]
            - [ addChild, [@sonata.news.admin.comment]]
            - [ setCommentManager, [@sonata.news.manager.comment]]
    bde.admin.lost_property:
        class: Application\BDEBundle\Admin\LostPropertyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Vie Étudiante", label: "Objets Trouvés", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Application\BDEBundle\Entity\LostProperty
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationBDEBundle]]
    bde.admin.bargain:
        class: Application\BDEBundle\Admin\BargainAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Vie Étudiante", label: "Bons Plans", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Application\BDEBundle\Entity\Bargain
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationBDEBundle]]