parameters:

services:
    bde.admin.product:
        class: Application\BDEBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Breguet Shop", label: "Article", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Application\BDEBundle\Entity\Product
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationBDEBundle]]
    bde.admin.product_category:
        class: Application\BDEBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Breguet Shop", label: "Catégorie", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Application\BDEBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationBDEBundle]]
    bde.admin.club:
        class: Application\BDEBundle\Admin\ClubAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Associatif", label: "Club", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Application\BDEBundle\Entity\Club
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationBDEBundle]]
    bde.admin.event:
        class: Application\BDEBundle\Admin\EventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Associatif", label: "Événement", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Application\BDEBundle\Entity\Event
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationBDEBundle]]