Application\BDEBundle\Entity\Club:
    properties:
        email:
            - Email: ~
        shortcode:
            - Length:
                min: 2
        title:
            - Length:
                min: 3
