Application\BDEBundle\Entity\Club:
    properties:
        email:
            - Email: ~
        shortcode:
            - Length:
                min: 2
        title:
            - Length:
                min: 3
        president:
            - Range:
                min: 1000000
                max: 9999999
                minMessage: Ce n'est pas un numéro de carte valide
                maxMessage: Ce n'est pas un numéro de carte valide
                invalidMessage: Ce n'est pas un numéro de carte valide
