<?php

namespace Application\BDEBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BargainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BargainRepository extends EntityRepository
{
}
