<?php

namespace Application\BDEBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCategoryRepository extends EntityRepository
{
}
