<?php

namespace Application\PoudlardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClubHasPointsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubHasPointsRepository extends EntityRepository
{
}
