<?php

namespace Application\Sonata\BlockBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TextBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditableTextBlockRepository extends EntityRepository
{
}
