<?php

namespace Application\ESIEEGamesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PointsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointsRepository extends EntityRepository
{
}
