<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var integer $resource
     */
    protected $resource;

    /**
     * @var integer $week_before_exam
     */
    protected $week_before_exam = 1;

    /**
     * @var \Application\BDEBundle\Entity\Club
     */
    private $club;

    /**
     * @var string
     */
    private $google_id;

    /**
     * @var string
     */
    private $google_access_token;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param $resource
     */
    public function setResource(\Application\BDEBundle\Entity\Resource $resource)
    {
        $this->resource = $resource;

        return $this;
    }

    /**
     * @return Resource
     */
    public function getResource()
    {
        return $this->resource;
    }

    /**
     * @param int $weekBeforeExam
     */
    public function setWeekBeforeExam($weekBeforeExam)
    {
        $this->weekBeforeExam = $weekBeforeExam;

        return $this;
    }

    /**
     * @return int
     */
    public function getWeekBeforeExam()
    {
        return $this->weekBeforeExam;
    }

    public function __toString()
    {
        return ''.(($this->lastname !== null) ? $this->lastname : (($this->firstname !== null) ? $this->firstname : $this->username));
    }

    /**
     * Set club
     *
     * @param \Application\BDEBundle\Entity\Club $club
     * @return User
     */
    public function setClub(\Application\BDEBundle\Entity\Club $club = null)
    {
        $this->club = $club;

        return $this;
    }

    /**
     * Get club
     *
     * @return \Application\BDEBundle\Entity\Club 
     */
    public function getClub()
    {
        return $this->club;
    }

    /**
     * Set google_id
     *
     * @param string $googleId
     * @return User
     */
    public function setGoogleId($googleId)
    {
        $this->google_id = $googleId;

        return $this;
    }

    /**
     * Get google_id
     *
     * @return string 
     */
    public function getGoogleId()
    {
        return $this->google_id;
    }

    /**
     * Set google_access_token
     *
     * @param string $googleAccessToken
     * @return User
     */
    public function setGoogleAccessToken($googleAccessToken)
    {
        $this->google_access_token = $googleAccessToken;

        return $this;
    }

    /**
     * Get google_access_token
     *
     * @return string 
     */
    public function getGoogleAccessToken()
    {
        return $this->google_access_token;
    }
}
