<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var integer $resource
     */
    protected $resource;

    /**
     * @var integer $week_before_exam
     */
    protected $week_before_exam = 1;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param $resource
     */
    public function setResource(\Application\BDEBundle\Entity\Resource $resource)
    {
        $this->resource = $resource;
    }

    /**
     * @return Resource
     */
    public function getResource()
    {
        return $this->resource;
    }

    /**
     * @param int $weekBeforeExam
     */
    public function setWeekBeforeExam($weekBeforeExam)
    {
        $this->weekBeforeExam = $weekBeforeExam;
    }

    /**
     * @return int
     */
    public function getWeekBeforeExam()
    {
        return $this->weekBeforeExam;
    }
}