<?php

namespace Application\ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LostPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LostPropertyRepository extends EntityRepository
{
}
