services:
    sonata_user.registration.form.type:
        class: Application\Sonata\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: sonata_user_registration }

    application_sonata_user.admin.user:
        class: Application\Sonata\UserBundle\Admin\UserAdmin
        arguments: [~, Application\Sonata\UserBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Utilisateurs, label_translator_strategy: "sonata.admin.label.strategy.underscore"}
        calls:
            - [ setTranslationDomain, [SonataUserBundle]]
            - [ setUserManager, [@fos_user.user_manager]]
            
    application_sonata_user.twig.user_helper:
        class: Application\Sonata\UserBundle\Services\UserHelper
        tags :
            - { name: twig.extension }

    application_sonata_user.security.user_provider:
        class     : Application\Sonata\UserBundle\Security\Core\User\FOSUBUserProvider
        arguments : ['@fos_user.user_manager', '@doctrine.orm.entity_manager', '@validator', { google: google_id }]
