FOS\UserBundle\Model\User:
    properties:
        email:
            - NotBlank: ~
            - Regex:
                pattern: "/^[a-z\.-]+[0-9]{0,2}@edu\.esiee\.fr$/"
                message: Vous devez avoir un mail @edu.esiee.fr
