FOS\UserBundle\Model\User:
    properties:
        email:
            - NotBlank: ~
            - Regex:
                pattern: "/^[a-z0-9\.-]+@edu\.esiee\.fr$/"
                message: Vous devez avoir un mail @edu.esiee.fr
