FOS\UserBundle\Model\User:
    properties:
        email:
        	- NotBlank: ~
            - Regex:
                pattern: "/^[a-z\.-]+@edu\.esiee\.fr$/"
                message: Vous devez avoir un mail @edu.esiee.fr
